spring:
  data:
    mongodb:
      host: wrex.rocks
      port: 27017
      database: wrex

wrex:
  nlp:
    url: http://wrex.rocks:5000/getNouns
  userCorrelations:
    url: http://wrex.rocks:5001/runModel
  slack:
    prompt:
      url: http://wrex.rocks:3000/prompt
    auth:
      url: https://slack.com/api/oauth.access
