spring:
  data:
    mongodb:
      host: wrex.rocks
      port: 27017
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: wrex

wrex:
  nlp:
    url: http://wrex.rocks:5000/getNouns
  userCorrelations:
    url: http://wrex.rocks:5001/runModel
  slack:
    prompt:
      url: http://wrex.rocks:3000/prompt
    recommendationNotify:
      url: http://wrex.rocks:3000/recommendation-notify
    auth:
      url: https://slack.com/api/oauth.access
