server:
  port: 8080
  servlet:
    context-path: /api
spring:
  data:
    mongodb:
      host: wrex-db
      port: 27017
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: wrex

wrex:
  nlp:
    url: http://wrex-nlp:5000/getNouns
  userCorrelations:
    url: http://wrex-user-correlation:5001/runModel
  slack:
    prompt:
      url: http://wrex-slack-app:3000/prompt
    auth:
      url: https://slack.com/api/oauth.access
      clientId: ${SLACK_CLIENT_ID}
      clientSecret: ${SLACK_CLIENT_SECRET}
  statusPromptSeconds: 604800
  statusPromptCheckSeconds: 3600

