server:
  port: 8080
  servlet:
    context-path: /api
spring:
  data:
    mongodb:
      host: wrex-db
      port: 27017
      database: wrex

wrex:
  nlp:
    url: http://wrex-nlp:5000/getNouns
  userCorrelations:
    url: http://wrex-user-correlation:5001/runModel
